#import "@preview/cetz:0.5.2": canvas, draw
#set page(width: auto, height: auto, margin: 8pt)
#set text(size: 12pt)
#canvas({
  draw.circle((0, 0), radius: 4, fill: rgb("f3e9e9"), stroke: none)
  draw.circle((0, 0), radius: 2, fill: white, stroke: none)
  draw.line((-4.6, 0), (4.6, 0), mark: (end: ">"))
  draw.line((0, -4.6), (0, 4.6), mark: (end: ">"))
  draw.content((4.8, 0.3), [$x$])
  draw.content((0.3, 4.6), [$y$])
  draw.circle((0, 0), radius: 4, stroke: (dash: "dashed"))
  draw.circle((0, 0), radius: 2, stroke: (dash: "dashed"))
  draw.content((0, 2.6), [$r = 1$ excluído])
  draw.content((0, -4.6), [$r = 2$ excluído])
  draw.content((0, -5.3), [domínio: $1 < r < 2$])
})
