#import "@preview/cetz:0.5.2": canvas, draw
#set page(width: auto, height: auto, margin: 8pt)
#set text(size: 12pt)
#canvas({
  let c = 2 * calc.sqrt(2)
  let p = calc.sqrt(2)
  draw.line((-3.3, 0), (3.3, 0), mark: (end: ">"))
  draw.line((0, -3.3), (0, 3.3), mark: (end: ">"))
  draw.content((3.5, 0.3), [$x$])
  draw.content((0.3, 3.4), [$y$])
  draw.circle((0, 0), radius: 2)
  draw.line((0.1, c - 0.1), (c - 0.1, 0.1), stroke: rgb("28716c"))
  draw.line((-c + 0.1, -0.1), (-0.1, -c + 0.1), stroke: (paint: rgb("28716c"), dash: "dashed"))
  draw.circle((p, p), radius: 3pt, fill: rgb("8c2d3b"), stroke: none)
  draw.circle((-p, -p), radius: 3pt, fill: rgb("8c2d3b"), stroke: none)
  draw.content((2.6, 2.9), [$x + y = 2 sqrt(2)$])
  draw.content((-2.6, -2.9), [$x + y = -2 sqrt(2)$])
  draw.content((0, -3.8), [$x^2 + y^2 = 4$; contactos em $plus.minus(sqrt(2), sqrt(2))$])
})
