stateDiagram-v2
  direction TB
  state "Esperar RR(1)" as Aguarda1
  state "Esperar RR(0)" as Aguarda0
  [*] --> Aguarda1: Enviar I(0)
  Aguarda1 --> Aguarda1: Timeout: retransmitir I(0)
  Aguarda1 --> Aguarda0: RR(1): enviar I(1)
  Aguarda0 --> Aguarda0: Timeout: retransmitir I(1)
  Aguarda0 --> Aguarda1: RR(0): enviar I(0)
